api_platform:
  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity/'
  elasticsearch:
    hosts:
      - '%env(ES_HOST)%'

when@prod:
  api_platform:
    enable_docs: false
    graphql:
      graphql_playground:
        enabled: false
      graphiql:
        enabled: false
